### ISSUE TITLE
errors in training related to the structure of doc_feature_dict

### ISSUE THREAD

**Issue by hagreven** [danyang-liu/KRED#11]
At the attempt of training (single-task, user2item) I encountered multiple errors (KeyError: ‘‘, IndexError: tuple index out of range) thrown from the following functions in News_embedding.py:
    • get_entities_ids
    • get_entities_nums
    • get_position
    • get_type
    • get_context_vector

Those errors seem to be related to the structure of doc_feature_dict or rather news_features in function build_news_features_mind in utils.util.py.
Errors occur for execution from the notebook as for execution from main.py.

**Comment by danyang-liu** [comment]
sorry, it seems that I pushed the wrong branch, I will fix it soon, and then tell you, thanks a lot!

**Comment by danyang-liu** [comment]
I update the code, fixed the bugs, thanks, you can try again!

**Comment by hagreven** [comment]
Thanks a lot! That solved my problem. I had to make some small fixes after your update but got it to work. I created a pull request with the fixes.
