### ISSUE TITLE
kg的下载链接

### ISSUE THREAD

**Issue by 1607722534** [danyang-liu/KRED#15]
能不能给一下kg文件的下载链接

**Comment by IMLHF** [comment]
https://kredkg.blob.core.windows.net/wikidatakg/kg.zip

**Comment by wylapp** [comment]
Hi, do you still preserve the kg.zip file? The link is expired; I can not download it. Please contact me if you can share it. Thanks!
你好，请问图谱数据你还有吗？链接挂掉了。

**Comment by 66246764** [comment]
> Hi, do you still preserve the kg.zip file? The link is expired; I can not download it. Please contact me if you can share it. Thanks! 你好，请问图谱数据你还有吗？链接挂掉了。

您好，请问你有找到这部分数据吗

**Comment by wylapp** [comment]
> > Hi, do you still preserve the kg.zip file? The link is expired; I can not download it. Please contact me if you can share it. Thanks! 你好，请问图谱数据你还有吗？链接挂掉了。
> 
> 您好，请问你有找到这部分数据吗

抱歉，没有找到，作者也没有回复

**Comment by 66246764** [comment]
好的，谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月3日(星期天) 晚上8:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [danyang-liu/KRED] kg的下载链接 (#15)





   
Hi, do you still preserve the kg.zip file? The link is expired; I can not download it. Please contact me if you can share it. Thanks! 你好，请问图谱数据你还有吗？链接挂掉了。
  
您好，请问你有找到这部分数据吗
  
抱歉，没有找到，作者也没有回复
