### ISSUE TITLE
data_loader error

### ISSUE THREAD

**Issue by wingz1** [danyang-liu/KRED#2]
Wondering if line 28 of your dataloader.py should be this:

entity_num = int(fp_entity2id.readline().split()[1]) 

What you had before gives this error:

entity_num = int(fp_entity2id.readline().split('\n')[0])
ValueError: invalid literal for int() with base 10: 'e_0\t0'

Or, have you changed the desired format for the entity2id.txt file recently and didn't upload a new demo.zip?  
In the current demo.zip, its e.g. "e33    33".

**Comment by TJ2364** [comment]
I found this problem too, the sorce program is just too bad!

**Comment by danyang-liu** [comment]
sorry for this, I think I uploaded the wrong data.
