### ISSUE TITLE
Another data_loader error with demo

### ISSUE THREAD

**Issue by wingz1** [danyang-liu/KRED#3]
KRED/utils/data_loader.py", line 40, in construct_adj    
entity_adj[int(key)].append(int(kg[key][i][0]))
ValueError: invalid literal for int() with base 10: 'e_0'

You are trying to int convert a string value of e_0, which doesn't work.

So again, wondering if the demo.zip txt files are outdated for this latest code?

Thanks.

**Comment by danyang-liu** [comment]
updated the demo data
