### ISSUE TITLE
About Result

### ISSUE THREAD

**Issue by FloatingMaple** [danyang-liu/KRED#7]
I also encounter the indexerror，then i skip them（they are some i=0, key=27728)。
In multi-task training，i got result：

learning rate 0.0001 l2_regular 1e-05
epoch 0 loss 0.9009023308753967
auc score:0.3821239489255684
ndcg score:0.18594372373009818
epoch 1 loss 0.8992260694503784
auc score:0.36748676424789783
ndcg score:0.1543790261891068
epoch 2 loss 0.8994665145874023
auc score:0.3586110246029275
ndcg score:0.19249648327055827
Early stopping

In single_task training, i got result:

learning rate 0.0001 l2_regular 1e-05
epoch 0 loss 0.9013379812240601
auc score:0.49532855808159454
ndcg score:0.18516682478169805
epoch 1 loss 0.8994540572166443
auc score:0.4968857053877297
ndcg score:0.17322098298863342
epoch 2 loss 0.9021483659744263
auc score:0.5010900031142946
ndcg score:0.1883194694252664
epoch 3 loss 0.8973627090454102
auc score:0.5239800685144815
ndcg score:0.18048882217871887
epoch 4 loss 0.8998004198074341
auc score:0.530909374026783
ndcg score:0.1822326944188028
epoch 5 loss 0.8982971906661987
auc score:0.5436001245717845
ndcg score:0.1822326944188028
epoch 6 loss 0.8954596519470215
auc score:0.5381501090003115
ndcg score:0.19528657538962646
epoch 7 loss 0.8978533744812012
auc score:0.5390843973839925
ndcg score:0.2291433486497505
Early stopping

Process finished with exit code 0

The result seems not good enough.

**Comment by danyang-liu** [comment]
The demo data is just for testing the code, not enough for getting good results.
